### ISSUE TITLE
jQuery 3.3.1 released. Please upgrade gem

### ISSUE THREAD

**Issue by Sega100500** [rails/jquery-rails#246]
jQuery 3.3.1 released. Please upgrade gem

**Comment by kstratis** [comment]
Yeap. Gem should definitely be upgraded.

**Comment by jeremy** [comment]
Please do put together a pull request! Previous version upgrade, for example: https://github.com/rails/jquery-rails/commit/6430f5f24985ffafa535269c5bca21aff63e27cf

**Comment by RouL** [comment]
@jeremy last time I made a pull request for that, the issue got closed mentioning this:
https://github.com/rails/jquery-rails/blob/master/CONTRIBUTING.md#updating-jquery
According to that, pull requests for new jQuery versions are not accepted due to security reasons.

Also see: https://github.com/rails/jquery-rails/pull/247

PS: Is this project still active?

**Comment by jeremy** [comment]
Thanks @RouL, that's right. @rafaelfranca has been bumping the version and verifying the JS upstream.

**Comment by rafaelfranca** [comment]
Done!
